### ISSUE TITLE
plane-split 0.4.0 on crates.io contains a Cargo.toml.orig file

### ISSUE THREAD

**Issue by staktrace** [kvark/plane-split#3]
Not the end of the world, but probably unintentional. STR:

```
wget https://crates.io/api/v1/crates/plane-split/0.4.0/download
mv download download.tar.gz
tar tf download.tar.gz
```

check listing, it includes this file:
`plane-split-0.4.0/Cargo.toml.orig`

edit: fix typo in 'download'

**Comment by kvark** [comment]
Well, at least it didn't grab `~/Documents.passwords.txt`

**Comment by staktrace** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1369156:

> It's a bad idea in general to have files named *.orig and *.rej in the tree
> since those extensions are used by mercurial for conflicts.  Especially in
> this case when there is a third_party/rust/bindgen/Cargo.toml file, which
> is why I assume the above is a mistake.

**Comment by kvark** [comment]
@staktrace would you be fine with waiting for `euclid-0.14` to come out (and `plane-split 0.5` accordingly)?

**Comment by staktrace** [comment]
@kvark I personally don't care much but I'm not sure if it will interfere with other people's mercurial workflow. If it does interfere with their workflow then this will basically block all WR updates into m-c until resolved.

**Comment by kvark** [comment]
Fixed in https://crates.io/crates/plane-split/0.4.1

**Comment by staktrace** [comment]
Thanks!
